/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_advantej_ndksample_Helper */

#ifndef _Included_com_advantej_ndksample_Helper
#define _Included_com_advantej_ndksample_Helper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_advantej_ndksample_Helper
 * Method:    doAwesomeTask
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_advantej_ndksample_Helper_doAwesomeTask
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
